[package]
name = "stdx"
version = "0.0.1"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "The missing batteries of Rust"
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "0.3.0"
docopt = "0.6.67"
env_logger = "0.3.1"
flate2 = "0.2.7"
hyper = "0.6.1"
itertools = "0.3.21"
lazy_static = "0.1.11"
libc = "0.1.8"
log = "0.3.1"
num = "0.1.25"
rand = "0.3.8"
regex = "0.1.39"
rustc-serialize = "0.3.15"
semver = "0.1.19"
tempdir = "0.3.4"
time = "0.1.3"
toml = "0.1.21"
url = "0.2.35"
