[package]
name = "stdx"
version = "0.115.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "The missing batteries of Rust"
license = "MIT/Apache-2.0"

[dependencies]
bitflags = "=0.7.0"
byteorder = "=1.0.0"
chrono = { version = "=0.3.0", features = ["serde"] }
clap = "=2.20.1"
error-chain = "=0.8.1"
json = "=0.11.5"
lazy_static = "=0.2.2"
libc = "=0.2.20"
log = "=0.3.6"
ndarray = { version = "=0.8.0", features = ["serde"] }
num = "=0.1.36"
rand = "=0.3.15"
rayon = "=0.6.0"
regex = "=0.2.1"
reqwest = "=0.4.0"
serde = "=0.9.10"
tempdir = "=0.3.5"
toml = "=0.3.1"
url = "=1.4.0"

# Supplemental dependencies
env_logger = "=0.4.0"
serde_derive = "=0.9.10"
serde_json = "=0.9.8"
