[package]
name = "stdx"
version = "0.0.1"
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "The missing batteries of Rust"
license = "MIT/Apache-2.0"

[features]
default = [
    "bitflags",
    "docopt",
    "env_logger",
    "itertools",
    "lazy_static",
    "libc",
    "log",
    "num",
    "rand",
    "regex",
    "rustc-serialize",
    "semver",
    "tempdir",
    "time",
    "toml",
    "url",
]
all = ["default", "flate2", "hyper"]

[dependencies]
bitflags = { version = "0.3.0", optional = true }
docopt = { version = "0.6.67", optional = true }
env_logger = { version = "0.3.1", optional = true }
flate2 = { version = "0.2.7", optional = true }
hyper = { version = "0.6.1", optional = true }
itertools = { version = "0.3.21", optional = true }
lazy_static = { version = "0.1.11", optional = true }
libc = { version = "0.1.8", optional = true }
log = { version = "0.3.1", optional = true }
num = { version = "0.1.25", optional = true }
rand = { version = "0.3.8", optional = true }
regex = { version = "0.1.39", optional = true }
rustc-serialize = { version = "0.3.15", optional = true }
semver = { version = "0.1.19", optional = true }
tempdir = { version = "0.3.4", optional = true }
time = { version = "0.1.30", optional = true }
toml = { version = "0.1.21", optional = true }
url = { version = "0.2.35", optional = true }
